# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKvfc-voUQEa80mt6upXCAOZG-6yjZYq
"""

import streamlit as st
import pandas as pd
import os
from datetime import datetime, date, time as dtime
import uuid

# -----------------------
# Paths & constants
# -----------------------
APP_DIR = os.path.dirname(__file__)
DATA_DIR = os.path.join(APP_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)

ORDERS_PATH = os.path.join(DATA_DIR, "orders.csv")
ORDER_ITEMS_PATH = os.path.join(DATA_DIR, "order_items.csv")

REQUIRED_COLS = ["S.No", "Item Category", "Item Name", "Quantity available in stock", "Price"]

# -----------------------
# Utilities
# -----------------------
def ensure_orders_files():
    """Create empty order CSVs if missing (inventory is never saved/updated)."""
    if not os.path.exists(ORDERS_PATH):
        pd.DataFrame(
            columns=["order_id", "customer_name", "phone", "pickup_date", "pickup_time", "total", "created_at"]
        ).to_csv(ORDERS_PATH, index=False)
    if not os.path.exists(ORDER_ITEMS_PATH):
        pd.DataFrame(
            columns=["order_id", "S.No", "Item Category", "Item Name", "qty", "unit_price", "line_total"]
        ).to_csv(ORDER_ITEMS_PATH, index=False)

def read_inventory_from_filelike(upload) -> pd.DataFrame:
    """Read uploaded CSV/Excel file and return a normalized DataFrame."""
    name = upload.name.lower()
    if name.endswith(".xlsx") or name.endswith(".xls"):
        df = pd.read_excel(upload)
    else:
        df = pd.read_csv(upload)

    missing = [c for c in REQUIRED_COLS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    # Coerce types / clean
    df["S.No"] = pd.to_numeric(df["S.No"], errors="coerce").astype("Int64")
    df["Quantity available in stock"] = (
        pd.to_numeric(df["Quantity available in stock"], errors="coerce").fillna(0).astype(int)
    )
    df["Price"] = pd.to_numeric(df["Price"], errors="coerce").fillna(0.0).astype(float)
    df = df.dropna(subset=["Item Name"]).copy()
    return df

def add_to_cart(item_row: pd.Series, qty: int):
    key = int(item_row["S.No"]) if pd.notna(item_row["S.No"]) else hash(item_row["Item Name"])
    cart = st.session_state.cart
    if key in cart:
        new_qty = cart[key]["qty"] + qty
        cart[key]["qty"] = new_qty
        cart[key]["line_total"] = round(new_qty * cart[key]["unit_price"], 2)
    else:
        cart[key] = {
            "S.No": int(item_row["S.No"]) if pd.notna(item_row["S.No"]) else None,
            "Item Category": item_row["Item Category"],
            "Item Name": item_row["Item Name"],
            "qty": qty,
            "unit_price": float(item_row["Price"]),
            "line_total": round(qty * float(item_row["Price"]), 2),
        }

def cart_to_dataframe():
    if not st.session_state.cart:
        return pd.DataFrame(columns=["Item Category", "Item Name", "Qty", "Unit Price", "Line Total"])
    rows = []
    for v in st.session_state.cart.values():
        rows.append([v["Item Category"], v["Item Name"], v["qty"], v["unit_price"], v["line_total"]])
    return pd.DataFrame(rows, columns=["Item Category", "Item Name", "Qty", "Unit Price", "Line Total"])

def cart_total():
    return round(sum(v["line_total"] for v in st.session_state.cart.values()), 2)

def persist_order(order_id: str, name: str, phone: str, p_date: date, p_time: dtime, total: float):
    """Append order header/items to CSVs. Inventory is NOT modified."""
    ensure_orders_files()

    # Header
    orders_df = pd.read_csv(ORDERS_PATH)
    new_order = pd.DataFrame([{
        "order_id": order_id,
        "customer_name": name,
        "phone": phone,
        "pickup_date": str(p_date),
        "pickup_time": p_time.strftime("%H:%M"),
        "total": total,
        "created_at": datetime.now().isoformat(timespec="seconds"),
    }])
    orders_df = pd.concat([orders_df, new_order], ignore_index=True)
    orders_df.to_csv(ORDERS_PATH, index=False)

    # Items
    items_df = pd.read_csv(ORDER_ITEMS_PATH)
    for v in st.session_state.cart.values():
        items_df.loc[len(items_df)] = [
            order_id, v.get("S.No"), v["Item Category"], v["Item Name"], v["qty"], v["unit_price"], v["line_total"]
        ]
    items_df.to_csv(ORDER_ITEMS_PATH, index=False)

def reset_cart():
    st.session_state.cart = {}

# -----------------------
# Streamlit App
# -----------------------
st.set_page_config(page_title="Grocery Pickup (No Online Payment)", page_icon="🛒", layout="wide")

# Init session state
if "cart" not in st.session_state:
    st.session_state.cart = {}
if "inventory" not in st.session_state:
    st.session_state.inventory = None  # user must upload each run (or add a default below if you like)

st.title("🛒 Grocery Pickup — Order Online, Pay In-Store")

with st.sidebar:
    st.header("Upload Inventory (Read-Only)")
    uploaded = st.file_uploader("Upload CSV or Excel", type=["csv", "xlsx", "xls"])
    if uploaded is not None:
        try:
            st.session_state.inventory = read_inventory_from_filelike(uploaded)
            st.success("Inventory loaded (read-only). The app will NOT change your file.")
        except Exception as e:
            st.error(f"Failed to read inventory: {e}")

    st.markdown("---")
    st.subheader("Admin (Local)")
    ensure_orders_files()
    st.caption("Orders are appended to local CSVs:")
    st.code(f"{ORDERS_PATH}\n{ORDER_ITEMS_PATH}", language="text")

# Require inventory
if st.session_state.inventory is None:
    st.info("Please upload your inventory file to begin.")
    st.stop()

# -----------------------
# Catalog & Add to Cart
# -----------------------
inv = st.session_state.inventory.copy()
left, right = st.columns([2, 1])

with left:
    st.subheader("Browse Items")
    categories = ["All"] + sorted(inv["Item Category"].dropna().unique().tolist())
    category = st.selectbox("Filter by category", categories, index=0)
    if category != "All":
        inv = inv[inv["Item Category"] == category]

    st.dataframe(
        inv[["S.No", "Item Category", "Item Name", "Quantity available in stock", "Price"]]
        .reset_index(drop=True),
        use_container_width=True
    )

    with st.form("add_to_cart_form", clear_on_submit=True):
        st.markdown("### Add to cart")
        item_names = inv["Item Name"].tolist()
        if len(item_names) == 0:
            st.info("No items available in this category.")
        else:
            chosen_name = st.selectbox("Item", item_names)
            item_row = inv[inv["Item Name"] == chosen_name].iloc[0]
            max_qty = int(item_row["Quantity available in stock"])
            qty = st.number_input("Quantity", min_value=1, max_value=max_qty if max_qty > 0 else 1, value=1, step=1)
            submitted = st.form_submit_button("Add")
            if submitted:
                if max_qty <= 0:
                    st.warning("Sorry, this item is out of stock (per your sheet).")
                else:
                    add_to_cart(item_row, int(qty))
                    st.success(f"Added {qty} × {chosen_name} to cart.")

with right:
    st.subheader("Your Cart")
    cart_df = cart_to_dataframe()
    st.dataframe(cart_df, use_container_width=True, hide_index=True)
    st.metric("Total", f"${cart_total():,.2f}")
    if st.button("Clear cart"):
        reset_cart()
        st.info("Cart cleared.")

# -----------------------
# Checkout (no payment online)
# -----------------------
st.markdown("---")
st.header("Confirm Order (Pay In-Store)")

with st.form("checkout_form", clear_on_submit=False):
    c1, c2 = st.columns(2)
    with c1:
        customer_name = st.text_input("Full Name")
        phone = st.text_input("Phone")
    with c2:
        p_date = st.date_input("Pickup Date", value=date.today())
        p_time = st.time_input("Pickup Time", value=dtime(17, 0))

    agree = st.checkbox("I understand that payment is in-store only (no online payment).")
    confirm = st.form_submit_button("Place Order")

    if confirm:
        if len(st.session_state.cart) == 0:
            st.warning("Your cart is empty.")
        elif not customer_name or not phone or not agree:
            st.warning("Please fill your details and acknowledge the no-online-payment policy.")
        else:
            # Validate against the uploaded (read-only) stock for this single order
            ok = True
            inv_now = st.session_state.inventory
            for v in st.session_state.cart.values():
                row = inv_now[inv_now["Item Name"] == v["Item Name"]]
                if row.empty or int(row["Quantity available in stock"].iloc[0]) < v["qty"]:
                    ok = False
                    st.error(f"Not enough stock for {v['Item Name']} per your sheet. Please adjust quantity.")
                    break
            if ok:
                oid = f"ORD-{datetime.now().strftime('%Y%m%d-%H%M%S')}-{str(uuid.uuid4())[:8].upper()}"
                total = cart_total()
                persist_order(oid, customer_name, phone, p_date, p_time, total)

                receipt = pd.DataFrame({
                    "Field": ["Order ID", "Name", "Phone", "Pickup Date", "Pickup Time", "Total"],
                    "Value": [oid, customer_name, phone, str(p_date), p_time.strftime("%H:%M"), f"${total:,.2f}"]
                })
                st.success(f"Order placed! Your order ID is {oid}. Please pay at pickup.")
                st.download_button("Download Receipt (CSV)",
                                   data=receipt.to_csv(index=False).encode("utf-8"),
                                   file_name=f"{oid}_receipt.csv",
                                   mime="text/csv")
                reset_cart()

st.caption("Inventory shown is exactly what you uploaded. The app does not change it.")